### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by fabiennejh** [genostats/oz#1]
Bonjour !

I have a problem when trying to install Ravages, could you help me pleasev?

"installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Ravages/libs
** R
Error : (converti depuis l'avis) impossible de réencoder ‘p_valeur_moments_liu.r’ ligne 3
ERROR: unable to collate and parse R files for package ‘Ravages’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Ravages’
Error in i.p(...) : 
  (converti depuis l'avis) installation of package ‘/var/folders/5y/2ypkfxzj6j194w1_lxv5xjnc0000zt/T//Rtmp2mhtoP/file7d955a93e77/Ravages_0.1.tar.gz’ had non-zero exit status"

Fabienne

**Comment by Ozvan** [comment]
Hi Fabienne,

I'm really sorry, I did not see your issue before. 
We have made several changes since August. Is the package working now ?

Ozvan
