### ISSUE TITLE
SKAT-O extension

### ISSUE THREAD

**Issue by henry940926** [genostats/oz#2]
Dear author,

I came across your papers (the extension of burden test and SKAT to multinomial outcomes) which are amazing ideas. I wonder if you have thought/are in the process of extending the SKAT-O method to a multinomial outcome?

Many thanks

**Comment by Ozvan** [comment]
Many thanks for your message.
SKAT p-values are currently obtained through permutation procedures. This makes it difficult to integrate our SKAT extension into SKAT-O which tests for different contributions of SKAT and burden tests. In addition, when SKAT-O is significant, it is often mainly driven by either the burden or the SKAT test. Nevertheless, this question is of great interest and I would be happy to further talk about it.

Best,
Ozvan
