### ISSUE TITLE
Error regarding the path.data in RAVA.FIRST function

### ISSUE THREAD

**Issue by LaporteFab** [genostats/oz#3]
Hi @HervePerdry,

One of my student try to use the function RAVA.FIRST() without adjCADD within the bed.matrix. Unfortunatly, the function crashed when calling the "adjustedCADD.annotation" function with this error:
"the directory 'path.data' to download and use the necessary files for RAVA-FIRST analysis should be provided"

When looking at your code, i saw that the path.data given in RAVA.FIRST arguments is not passed down to the function "filter.adjustedCADD" and therefore to the function "adjustedCADD.annotation".

https://github.com/genostats/Ravages/blob/8898170d4c96bddfb592ba4e2117cbe67643a35b/R/RAVA_FIRST.r#L16
and
https://github.com/genostats/Ravages/blob/8898170d4c96bddfb592ba4e2117cbe67643a35b/R/filter_adjustedCADD.r#L9

Regards,
Fabien

**Comment by Ozvan** [comment]
Dear Fabien,

The issue has just been resolved in the GitHub version, thank you for pointing it out.

Best regards,
Ozvan
